### ISSUE TITLE
hugo image doesn't have git

### ISSUE THREAD

**Issue by poy** [GoogleCloudPlatform/cloud-builders-community#332]
## Affected builder image

`gcr.io/cloud-builders-community/hugo`

## Expected Behavior
Tried using hugo with PostCSS

## Actual Behavior

Got the following error:
```
Building sites … ERROR 2019/12/04 20:19:20 Failed to read Git log: Git executable not found in $PATH
ERROR 2019/12/04 20:19:22 Transformation failed: POSTCSS: failed to transform "scss/main.css" (text/css): PostCSS not found; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/
```

## Steps to Reproduce the Problem
```bash
git clone https://github.com/google/kf
cd kf
git checkout 48ad607a912ed8bb49618ec6984a3de5d1785147
git submodule update --init --recursive
docker run --rm -it -v $PWD:/workspace  -w /workspace/docs/kf.dev gcr.io/$(gcloud config get-value project)/hugo
```

**Comment by sanastos** [comment]
I don't think it's the responsibility of the hugo builder to have git. There are any number of possible build tools that can be used; we can't package them all, and not every build will need git. Better to leave it to the person using the container to ensure their specific needs are filled.

**Comment by syedashrafulla** [comment]
I think this should be reopened because the Hugo build as-is doesn't work with Cloud Build. Steps to reproduce:

- `git clone` the repo
- run `gcloud builds submit --config ~/cloud-builders-community/hugo/cloudbuild.yaml ~/cloud-builders-community/hugo/`
- run a Cloud Build that is

```
steps:
- name: 'gcr.io/$PROJECT_ID/hugo'
  args: ['-b', "https://ashraful.la"]
```

and get the following error message

```
Step #0: Status: Downloaded newer image for gcr.io/ashrafulla-website/hugo:latest
Step #0: gcr.io/ashrafulla-website/hugo:latest
Step #0: Building sites … ERROR 2020/11/24 16:33:59 Failed to read Git log: Git executable not found in $PATH
```

It's because `gcr.io/distroless/cc` is missing `git` (as it should be). but `git` is required for Hugo apparently (even the non-extended version). I'm also a container n00b, so I don't know how to add git to the distroless container.

**Comment by syedashrafulla** [comment]
Hugo's dependency on Git is [documented here](https://gohugo.io/variables/git/). That means the solution for this build is to always set `EnableGitInfo = false` in the `config.toml` of the Hugo website.

If Git info integration (which is pretty cool) is required, then the simplest thing to do seems to be to get out of the multistage business and move from `busybox` to `alpine`, so that the new `Dockerfile` is

```
FROM alpine
ENTRYPOINT ["/hugo"]
ENV HUGO_VERSION=0.73.0
RUN apk add --no-cache git libstdc++ libc6-compat
RUN wget -O- https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz | tar zx
```

The extra packages matter so that the extracted `hugo` can be run in Alpine (which is why the distroless package of choice in the first place was `cc`).
